#Dockerfile
# FROM node:13.12.0-alpine as build
FROM alpine:3.16
FROM node:latest
EXPOSE 3001
COPY . /opt/app
WORKDIR /opt/app/
RUN npm install
RUN npm install express
# RUN cd node_modules/
#RUN npm install express
#RUN npm audit fix
CMD ["node", "bree.js", "0.0.0.0", "--port", "3001"]
# FROM node:13.12.0-alpine

# EXPOSE 3001

# COPY . /opt/app

# WORKDIR /opt/app/backend-server/

# RUN npm install

# # RUN cd node_modules/

# RUN npm install express


# #CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]

#  CMD ["node", "server", "--host", "0.0.0.0", "--port", "3001"]




# production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/node_modules /usr/share/nginx/html/
# COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80 
# CMD ["nginx", "-g", "daemon off;"]